export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';
export const SET_REGION = 'SET_REGION';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
export const SIGN_OUT = 'SIGN_OUT';

export const SET_SOCKET = 'SET_SOCKET';

export const FETCH_RIDES_REQUEST = 'FETCH_RIDES_REQUEST';
export const FETCH_RIDES_SUCCESS = 'FETCH_RIDES_SUCCESS';
export const FETCH_RIDES_ERROR = 'FETCH_RIDES_ERROR';
export const FETCH_DIRECTIONS_SUCCESS = "FETCH_DIRECTIONS_SUCCESS";
export const FETCH_DIRECTIONS_REQUEST = "FETCH_DIRECTIONS_REQUES";